"use client";

import "./globals.css";

import "typeface-inter";

export const metadata = {
  title: "Ani Ghosal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
