"use client";

import "./globals.css";

import { useEffect } from "react"; // Import useEffect from React
import emailjs from "emailjs-com";
import "typeface-inter";

export const metadata = {
  title: "Ani Ghosal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    emailjs.init("YOUR_USER_ID_HERE"); // Replace with your actual email.js user ID
  }, []);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
